version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    environment:
      DOMAIN: goalification.click
    ports:
      - "80:80"
    volumes:
      - ./nginx/prod/nginx.init.default.conf:/etc/nginx/templates/default.conf.template
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >-
      certonly --reinstall --webroot --webroot-path=/var/www/certbot
      --email davidgasparyang@gmail.com --agree-tos --no-eff-email
      -d goalification.click
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
