FROM node:18-alpine as build
ARG project

WORKDIR /build
COPY package.json yarn.lock decorate-angular-cli.js ./
RUN yarn
COPY . .
RUN yarn build $project

FROM nginx:alpine
ARG project
COPY --from=build /build/dist/apps/$project ./usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
