name: Bot CI-CD
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_SECRET }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            echo "${{ secrets.ENV }}" > .env
            git pull origin main
            docker compose down
            docker compose -f compose.prod.yml --env-file ./env up --build -d --remove-orphans
            echo "Deleting old image(s)..."
            docker image prune -a -f
